### ISSUE TITLE
Does not work with latest hyperluminal-mem

### ISSUE THREAD

**Issue by html** [cosmos72/hyperluminal-db#1]
To load hyperluminal-db with quicklisp version of hyperluminal-mem it needs to change package dependencies from `hyperluminal-ffi` to `hyperluminal-mem-ffi` in db/package.lisp and some fixes in db/store.lisp at least.
Just try to load it and you'll see errors.

**Comment by cosmos72** [comment]
Fixed. Hyperluminal-db doesn't do much yet...
