### ISSUE TITLE
There seems no test suit running now

### ISSUE THREAD

**Issue by ailisp** [cosmos72/hyperluminal-db#2]
Hello. When I run the test suit as shown in readme, hyperluminal-mem and stmx pass all the tests. However, hyperluminal-db says:
```
CL-USER> (asdf:test-system :hyperluminal-db)
To load "hyperluminal-db-test":
  Load 1 ASDF system:
    hyperluminal-db-test
; Loading "hyperluminal-db-test"


Running test suite SUITE
 Didn't run anything...huh?
```
Is there something wrong with its test? My OS is ubuntu 16.04 x64. And Lisp implementation is SBCL 1.3.1 x64.
Thanks.

**Comment by cosmos72** [comment]
There has never been a test suite for hyperluminal-db.

Actually, hyperluminal-db development is currently stalled and, since it is still alpha, I am considering to drop it...
