### ISSUE TITLE
quickload/compilation fails under sbcl 2.0.0 and 2.0.6

### ISSUE THREAD

**Issue by EarwainBanadar** [cosmos72/hyperluminal-db#4]
Environment portacle with sbcl 2.0.0 or sbcl 2.0.6 native

quickload fails on store.lisp @ line 78

[package hyperluminal-db].....

; file: /usr/local/bin/portacle/all/quicklisp/local-projects/hyperluminal-db/db/store.lisp
; in: DEFVAR *P*
;     (DEFVAR HYPERLUMINAL-DB::*P* HYPERLUMINAL-MEM-FFI:+NULL-POINTER+)
; --> PROGN SB-IMPL::%DEFVAR SB-IMPL::%DEFVAR 
; ==>
;   '#.(SB-SYS:INT-SAP #X00000000)
; 
; caught ERROR:
                                        ;   Objects of type SB-SYS:SYSTEM-AREA-POINTER can't be dumped into fasl files.

Is there any hint to overcome this issue?

**Comment by cosmos72** [comment]
fixed in by defining `+null-pointer+` as `nil` in hyperluminal-mem commit https://github.com/cosmos72/hyperluminal-mem/commit/7d4c94733d395a08c82e830db670a2d7ed6fb69e
